### ISSUE TITLE
Force phone number for OTG handoffs

### ISSUE THREAD

**Issue by justinmiller24** [gmo/arc#14] opened 2016-10-31 17:04 UTC
Background:
- For the current OTG connection process on the ARC discipleship dashboard, there’s currently a list of channels that an OM can choose from (Phone #, Skype, WhatsApp, etc). It's currently populating from a database table with a "show for OTG" checkbox. Stacy would like to change it globally for all system users to remove all but one option (phone number). Mike believes this is as simple as one database query.

Tasks:
- On the ARC discipleship dashboard, remove all OTG channel options globally except for phone number

**Comment by mikegillis677** [comment] 2016-10-31 18:55
This is a duplicate of closed issue https://github.com/gmo/arc/issues/11.  These changes have already been performed.

**Closed by mikegillis677** 2016-10-31 18:55 UTC
Labels: needs-estimate
